// IMPORTANT: Base Module preview template.
// This file must NOT be modified or generated by the AI.
// Only src/App.tsx and src/components/* are overwritten at runtime.

module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
