// IMPORTANT: Base Module preview template.
// This file must NOT be modified or generated by the AI.
// Only src/App.tsx and src/components/* are overwritten at runtime.

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {},
  },
  plugins: [],
};
