// IMPORTANT: Base Module preview template.
// This file must NOT be modified or generated by the AI.
// Only src/App.tsx and src/components/* are overwritten at runtime.

import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
});
