// IMPORTANT: Base Module preview template.
// This file must NOT be modified or generated by the AI.
// Only src/App.tsx and src/components/* are overwritten at runtime.

import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App";
import "./index.css";

ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
