-- Add missing columns to conversations table
ALTER TABLE public.conversations 
ADD COLUMN IF NOT EXISTS mode text CHECK (mode IN ('explain', 'debug', 'project')),
ADD COLUMN IF NOT EXISTS last_active timestamp with time zone DEFAULT now();

-- Add missing columns to messages table
ALTER TABLE public.messages
ADD COLUMN IF NOT EXISTS model_used text,
ADD COLUMN IF NOT EXISTS token_est integer;

-- Create requests_log table
CREATE TABLE IF NOT EXISTS public.requests_log (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  model text,
  tokens_est integer,
  created_at timestamp with time zone DEFAULT now()
);

-- Create feedback table
CREATE TABLE IF NOT EXISTS public.feedback (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  message_id uuid REFERENCES public.messages(id) ON DELETE CASCADE,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  rating integer CHECK (rating IN (-1, 1)),
  comment text,
  created_at timestamp with time zone DEFAULT now()
);

-- Enable RLS on new tables
ALTER TABLE public.requests_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.feedback ENABLE ROW LEVEL SECURITY;

-- RLS Policies for requests_log
CREATE POLICY "Users can view own requests"
  ON public.requests_log
  FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own requests"
  ON public.requests_log
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- RLS Policies for feedback
CREATE POLICY "Users can view own feedback"
  ON public.feedback
  FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own feedback"
  ON public.feedback
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own feedback"
  ON public.feedback
  FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own feedback"
  ON public.feedback
  FOR DELETE
  USING (auth.uid() = user_id);