// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ryhhskssaplqakovldlp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ5aGhza3NzYXBscWFrb3ZsZGxwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1MjgzMjYsImV4cCI6MjA3NDEwNDMyNn0.TmS-KxWIPNUOjgYYfGbx-vW8by4VVI35UzpakBuy3L4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});